### ISSUE TITLE
Way to plot various values

### ISSUE THREAD

**Issue by Botoni** [kenjiqq/qq-nodes-comfyui#1]
Is there a way to plot values like VAE, clip, clip_vision models, etc.?

For example, if I want to compare SD1.5 and SDXL models, I need to to iterate not only the "model" value, but also the CLIP and VAE together with the model.

Compare VAEs alone would be useful too.

**Comment by kenjiqq** [comment]
I added VAE and CLIP axis converts now so one can change vae or clip in the grid.

I also added a axis-config.json to make it easy to just locally add new "Axis To X"  converter nodes for whatever you need, can just add whatever new type you want to the array in that file.

Not quite sure how to handle changing multiple things like model, vae and clip together for a single axis. The easiest would be if there are some existing nodes that just package multiple inputs into a single output, then we can just put that output in a  "Any List" and send it into the grid. Will look around a bit.

**Comment by Botoni** [comment]
That was fast, thank you for looking into it.

**Comment by kenjiqq** [comment]
you should now be able to send in multiple values like you wanted using these nodes https://github.com/kenjiqq/qq-nodes-comfyui?tab=readme-ov-file#axis-packing

**Comment by Botoni** [comment]
Awesome!
