### ISSUE TITLE
fail at XY Grid Accumulator node, KeyError: 'GridAnnotation'

### ISSUE THREAD

**Issue by whmc76** [kenjiqq/qq-nodes-comfyui#10]
!!! Exception during processing !!! 'GridAnnotation'
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_Torch24\ComfyUI\execution.py", line 350, in execute
    class_def = nodes.NODE_CLASS_MAPPINGS[class_type]
                ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'GridAnnotation'


![image](https://github.com/user-attachments/assets/45ae75a7-42b6-408d-aaa9-311e41ba4874)

**Comment by Latentnaut** [comment]
Same error, what was the solution?

**Comment by ExpertLove** [comment]
Install https://github.com/LEv145/images-grid-comfy-plugin repair this problem
