### ISSUE TITLE
For unknown reasons, only one image will be generated.

### ISSUE THREAD

**Issue by zpengcom** [kenjiqq/qq-nodes-comfyui#11]
I don't know what's wrong, the terminal doesn't report an error, and occasionally it generates the grid map normally, but not again, I've tried your workflow examples, and all of them can only generate a single map, I don't know what's wrong Is it a problem with the latest version of comfyui?

**Comment by kenjiqq** [comment]
Do you click the reset button before you want to make a new grid to reset the counter? (technically it has wrap around so if you make a grid of 4 images it should make it when the counter reaches 4/8/12 etc as well).
And if its not working what do you see in the Accumulator node, it should show each image as it stores them until it reaches the amount needed for the grid and then it generates and output the grid image

**Comment by zpengcom** [comment]
I clicked reset, and the following is the terminal content after importing the workflow:

`Using pytorch attention in VAE
Using pytorch attention in VAE
I:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
Requested to load SDXL
Loading 1 new model
loaded completely 0.0 4897.0483474731445 True
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  5.63it/s]
Requested to load AutoencoderKL
Loading 1 new model
loaded completely 0.0 159.55708122253418 True
Prompt executed in 17.65 seconds
`

It looks like the XY Grid Accumulator only produced one graph and it worked;
not sure if this has to do with transformers？

**Comment by kenjiqq** [comment]
That looks fine, i think it might be a misunderstanding about how it works, maybe you are just generating one image?
To confirm how its supposed to work:

- If you load the example workflow https://raw.githubusercontent.com/kenjiqq/qq-nodes-comfyui/main/workflows/xy-grid.png
- Then you click the reset button on the XY Grid Helper node just to make sure its cleared. 
- Now you are supposed to queue up the amount of images that goes into the grid, so for the example this should be 4 images. So you click the queue prompt button in comfy 4 times, each time you click it the counter on the reset button goes up by one and it will say 4 of 4 when you have queued up the correct amount.
- Then you wait for all 4 to generate, for each image generated the XY Grid Accumulator will display 1 more small image until all 4 are there and then the grid is outputted and displayed in the preview node

**Comment by zpengcom** [comment]
I get it: the workflow can't tell how many mesh images I want to generate, so I need to go click on the corresponding number of times to generate, and click RESET before the next round of mesh generation.
Everything is working fine, thank you very much!
