### ISSUE TITLE
XY Grid just outputting one image?

### ISSUE THREAD

**Issue by oliverban** [kenjiqq/qq-nodes-comfyui#12]
I am just getting one image in the output, not changed anything from the example workflow.

![brave_94p3fcPDi5](https://github.com/user-attachments/assets/61e03bef-fcf6-49e2-9008-6210f7c530bc)

**Comment by oliverban** [comment]
USER ERROR: Was using wrong Checkpoint!

**Comment by kenjiqq** [comment]
Check out the paragraph under the Example workflow explaining how it works. The tldr is that you must queue up the amount of images that go into the grid
