### ISSUE TITLE
Is it possible to create a multi LoRA vs X?

### ISSUE THREAD

**Issue by geocine** [kenjiqq/qq-nodes-comfyui#13]
I want to achieve the example below but I'm unable to load multiple LoRAs one by one

|                | seed: 1 | seed: 2 | seed: 3 |
|----------------|---------|---------|---------|
| lora_2000      |         |         |         |
| lora_2200      |         |         |         |
| lora_2400      |         |         |         |

**Comment by kenjiqq** [comment]
Here is an example workflow showing how you can do it 
![workflow (3)](https://github.com/user-attachments/assets/9f2227a4-9b56-4f13-913a-18884570a8a3)

**Comment by geocine** [comment]
I actually tried the same thing as you did but with Flux. It's only generating 1 lora image

![workflow (3)](https://github.com/user-attachments/assets/b8d7c092-b412-40e4-bad8-24dd867f553a)

**Comment by kenjiqq** [comment]
Check out this https://github.com/kenjiqq/qq-nodes-comfyui?tab=readme-ov-file#usage-instructions, probably just didn't queue up multiple images

**Comment by geocine** [comment]
That makes sense , totally did not read that. I just assume it batches all the needed images just like other XY plots. Thank you!
