### ISSUE TITLE
Getting error while trying to use XY Accumulator

### ISSUE THREAD

**Issue by xandrmoro** [kenjiqq/qq-nodes-comfyui#14]
When I'm trying to run the example workflow from https://raw.githubusercontent.com/kenjiqq/qq-nodes-comfyui/refs/heads/main/workflows/xy-grid.png (or any custom workflow) I'm getting that error at the end of the entire process (no other details in the console):

024-10-02 01:57:45,827 - root - ERROR - Traceback (most recent call last):
  File "I:\ai\comfyui\comfy\execution.py", line 356, in execute
    class_def = nodes.NODE_CLASS_MAPPINGS[class_type]
KeyError: 'GridAnnotation'

Got latest custom node and comfy installations

**Comment by kenjiqq** [comment]
Install https://github.com/LEv145/images-grid-comfy-plugin as mentioned here https://github.com/kenjiqq/qq-nodes-comfyui?tab=readme-ov-file#xy-grid
Will see if i have make a better error message here to indicate you need to install another node package

**Comment by FruitPigFoot** [comment]
yo i got the same error too!
even with plugins installed(was-node and images-grid)

!!! Exception during processing !!! 'GridAnnotation'
Traceback (most recent call last):
  File "/home/aiaiaiaiai/comfyui/execution.py", line 356, in execute
    class_def = nodes.NODE_CLASS_MAPPINGS[class_type]
KeyError: 'GridAnnotation'

**Comment by Latentnaut** [comment]
Same error, please help!

**Comment by Latentnaut** [comment]
> Install https://github.com/LEv145/images-grid-comfy-plugin as mentioned here https://github.com/kenjiqq/qq-nodes-comfyui?tab=readme-ov-file#xy-grid Will see if i have make a better error message here to indicate you need to install another node package

Ey @kenjiqq , there is a real error here. 'GridAnnotation' is poping up. Could you please take a look? Thank you!

**Comment by kenjiqq** [comment]
> > Install https://github.com/LEv145/images-grid-comfy-plugin as mentioned here https://github.com/kenjiqq/qq-nodes-comfyui?tab=readme-ov-file#xy-grid Will see if i have make a better error message here to indicate you need to install another node package
> 
> Ey [@kenjiqq](https://github.com/kenjiqq) , there is a real error here. 'GridAnnotation' is poping up. Could you please take a look? Thank you!

@Latentnaut Yeah that should mean you haven't installed those image grid custom nodes mentioned. GridAnnotation is one of the nodes contained in that package. Should go away if you install it

**Comment by Latentnaut** [comment]
@kenjiqq my apologies, I installed all again from a fresh Comfy and it's working as expected. 

Thank you for your support and work!
