### ISSUE TITLE
How can I use more than 7 inputs?

### ISSUE THREAD

**Issue by Wonderflex** [kenjiqq/qq-nodes-comfyui#2]
Thank you for making these nodes.  Not really an issue, but more of a question.

Is there a way to use more than 7 inputs (input_a - input_g)?  

I normally like to run a test on condition averages using a floats 1-10 and use this system:

![image](https://github.com/kenjiqq/qq-nodes-comfyui/assets/112730878/7665f57d-740b-41b3-bdfe-cabf3b441e70)

Having the text box is great, because I can save off common float values as a comma separated list and then just paste them in when  needed instead of using the individual entry boxes from the text string.

The problem though is that it will only pass through the last number as the annotation if I connect it to the "any lists" node:

![image](https://github.com/kenjiqq/qq-nodes-comfyui/assets/112730878/cb64fa5d-27f7-4101-8278-404857f4c3e7)

![image](https://github.com/kenjiqq/qq-nodes-comfyui/assets/112730878/5c6a4e1c-f1c0-45a1-93e8-14a36f912634)

Thanks

**Comment by kenjiqq** [comment]
Yeah so the problem is that the annotations are only created at the final step when the grid image gets made, so at that point every value in the list is just "1.0" because you send the same value (the output of this CR node) to the list multiple times. It actually expects the complete list on every step so it expects to get [0.1, 0.2, 0.3] each step and instead is getting [0.1,0.1,0.1] first step, [0.2,0.2,0.2] seconds step etc.

**Comment by kenjiqq** [comment]
I just added a simple text splitter node, so you can do something like this
![split](https://github.com/kenjiqq/qq-nodes-comfyui/assets/599468/4f74236a-aadc-4806-b364-6ae2cfdd0b4a)

**Comment by Wonderflex** [comment]
You are awesome.  Thank you.

**Comment by FruitPigFoot** [comment]
@kenjiqq  i used text splitter to test multiple loras. However i always get the error saying the last one(model name) is in the directory, giving me the file not found error. 

when i had 10 loras, for example 1lora, 2lora ,..., 10lora, i get error saying 10lora is not in that directory. 
i tried with 9 loras, for example 1lora, 2lora, ...,9lora. I get the same error saying 9lora is not in that directory.
