### ISSUE TITLE
Bypassing or muting XY grid helper causes all processes to stop.

### ISSUE THREAD

**Issue by Wonderflex** [kenjiqq/qq-nodes-comfyui#4]
I have a few workflows built where sub-actions happen prior and after the XY Grid, and whenever I disable, or mute, the XY Grid Helper it will cause all other parts to not execute.  

Example: I am doing an img2img or face swap and want to run a crop prior to generating any images or the XY grid.  It may take a few tries until I find the exact crop I want.  If the XY Grid Helper is enabled the resize will run.  If the XY Grid Helper is bypassed, or muted, the resize won't work, even though the XY variables are unrelated to the resize.  I can work around this by disabling the Ksampler, but there are some workflows where I want to turn off the XY grid only, while allowing the K sampler to pass information along further down the line. 

Example workflow:
![exampleworkflow](https://github.com/kenjiqq/qq-nodes-comfyui/assets/112730878/99c853ad-41f4-4718-bdc6-3ff44e1f2858)

**Comment by Wonderflex** [comment]
Another workaround - reroute the outputs, leaving the XY Grid Helper on, and then muting the rerouters.

**Comment by kenjiqq** [comment]
some javascript crashed if it was bypassed or muted, so should be fine now

**Comment by Wonderflex** [comment]
> some javascript crashed if it was bypassed or muted, so should be fine now

Confirmed as working.  Thank you for being so responsive.
