### ISSUE TITLE
How to set samplers and schedulers?

### ISSUE THREAD

**Issue by gachapengames** [kenjiqq/qq-nodes-comfyui#5]
Hello. This workflow is really complex and I cannot figure out how to implement this. I am trying to setup: 

X: 4 Different sampler/schedulers such as Euler Normal, DPM++ Karras, etc. 
Y: 4 random seeds.

If you could provide a basic workflow, it would be much appreciated.

**Comment by kenjiqq** [comment]
The seeds should be pretty easy a seed is just an int, so you can just put 4 of those in a list, you can use the seed node from WAS nodes for instance
![image](https://github.com/kenjiqq/qq-nodes-comfyui/assets/599468/2250fa90-4dea-451b-82dd-62bea970f8cb)

The samplers are more difficult though. The multiple choices boxes are implemented very strangely and don't really work properly trying to input them so not sure how to do that

**Comment by kenjiqq** [comment]
ok i think i found a solution, added a any to any node, workflow here
![workflow (3)](https://github.com/kenjiqq/qq-nodes-comfyui/assets/599468/f81556c0-7d6b-48bb-9b83-9b33df139df5)

warning that this node is very hacky and disables all type checking that ensures your don't do anything incorrectly. So if you for instance type the sampler name wrong the KSampler node defaults to euler without any warning

**Comment by kenjiqq** [comment]
slightly updated workflow https://github.com/kenjiqq/qq-nodes-comfyui/blob/main/workflows/sampler-grid.png

**Comment by gachapengames** [comment]
> slightly updated workflow https://github.com/kenjiqq/qq-nodes-comfyui/blob/main/workflows/sampler-grid.png

Thanks for the effort!
