### ISSUE TITLE
TypeError: XYGridHelper.run() missing 1 required positional argument: 'index'

### ISSUE THREAD

**Issue by dodo522** [kenjiqq/qq-nodes-comfyui#6]
![image](https://github.com/kenjiqq/qq-nodes-comfyui/assets/66875947/8b747ed0-7f52-4d34-ab19-cdf3fdc4253b)
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/mnt/workspace/workgroup/longyu/project/model-comfyui/src/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/workspace/workgroup/longyu/project/model-comfyui/src/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/workspace/workgroup/longyu/project/model-comfyui/src/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: XYGridHelper.run() missing 1 required positional argument: 'index'

**Comment by kenjiqq** [comment]
There is not supposed to be a index input on that node, so you might have some old version of the node maybe? try updating and recreate the node

**Comment by Gerkinfeltser** [comment]
Hello! Using comfy portable on Windows 10, I'm seeing this as well.
I only just installed the addon so I've definitely got the latest. My error is the same as @dodo522's.

**Comment by signalstop** [comment]
Same issue with index error, using latest ComfiUI portable

**Comment by Botoni** [comment]
Same problem since some days ago on linux.

**Comment by kenjiqq** [comment]
I think this maybe was caused by how the extension JavaScript was loaded in an old way that might not have been compatible with the portable installation. So i think it should work now

**Comment by Gerkinfeltser** [comment]
Hey, thanks for the fix! Working on my end (using the portable version at least)! Thanks!
