### ISSUE TITLE
Cannot use multiple image accumulators in a workflow

### ISSUE THREAD

**Issue by hobojoker** [kenjiqq/qq-nodes-comfyui#9]
I'm trying to run multiple generations in a workflow, where the output of each generation sequence is sent to an image accumulator start/end -> Image Grid -> etc

The first sequence works great, but the 2nd image accumulator start does not run while the other image accumulator start is running and only processes once at the reset. The rest of the workflow is working fine and both image generation tasks are running and generating - the issue is the output is not being accumulated in the 2nd accumulator.

This would be less of an issue if I could just put them all into the same accumulator, but the images in the accumulator are extremely difficult to split up - I've thrown the output of the Image Accumulator End into nearly every image batch or list processing node I can most will throw an error: " 'list' object has no attribute 'shape' " when attempting to rebatch or turn it into a list that will work try try to split it.

**Comment by kenjiqq** [comment]
i think i fixed this at the same time as i redid the accumulator now to simplify it with some new features that just became available in comfy. There was built in caching in comfy that causes some strange behavior if you had multiple accumulator nodes in the same workflow
